# Site settings
title: Dev David
description: A little corner of cyberspace
# baseurl: "/"
url: "https://dcalano.dev"

# User settings
username: Hey, I'm David!
user_description: Personal landing page
user_title: Coder, Teacher, Space stuff
email: dcalano@protonmail.com
twitter_username:
github_username: dcalano
gplus_username:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
